services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./.data/mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: tarfu
      MYSQL_DATABASE: karpeliber
      MYSQL_USER: karpeliber
      MYSQL_PASSWORD: karpeliber
    ports:
      # This port only needs exposure for local DB client access.
      # Otherwise, the app will run without this port mapping.
      - '3306:3306'

  db_admin:
    image: adminer
    restart: always
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db

  web:
    build:
      context: .
      args:
        # This argument normally specified by docker-image.yaml CI.
        IMAGE_TAG: 'localdev-19700101T000000Z'
    restart: always
    volumes:
      - .:/code
      #- .:/code:delegated
      - ./.secrets:/secrets
    ports:
      - '127.0.0.1:8000:8000' # Django runserver
      - '127.0.0.1:7778:7778' # socat tunnel to DB (DB_TUNNEL_PORT in env.json)
    depends_on:
      - db
