name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  # Use env to hold repo name, then convert to lowercase in the run steps
  GITHUB_REPOSITORY: ${{ github.repository }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set image tag timestamp (format similar to ISO 8601)
        run: echo "IMAGE_TAG_TIMESTAMP=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${IMAGE_NAME}:${IMAGE_TAG_TIMESTAMP}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: serviceacct-regents-umich-edu
          password: ${{ secrets.GHCR_PAT }}

      - name: Tag image as latest
        run: docker tag ${IMAGE_NAME}:${IMAGE_TAG_TIMESTAMP} ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_NAME}:latest

      - name: Tag image with unique timestamp
        run: docker tag ${IMAGE_NAME}:${IMAGE_TAG_TIMESTAMP} ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_NAME}:${IMAGE_TAG_TIMESTAMP}

      - name: Push image with latest tag
        run: docker push ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_NAME}:latest

      - name: Push image with unique timestamp tag
        run: docker push ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_NAME}:${IMAGE_TAG_TIMESTAMP}
