name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
  release:
    types: [created]

env:
  # repo and image name, converted to lowercase in the run steps
  GITHUB_REPOSITORY: ${{ github.repository }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set image variables
        run: |
          echo "IMAGE_PATH=ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_NAME,,}" >> $GITHUB_ENV

      - name: Set tag variables
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG=$(date -u +'%Y%m%dT%H%M%SZ')
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "TAGGED_IMAGE=${IMAGE_PATH}:$TAG" >> $GITHUB_ENV
          echo "LATEST_TAG=${IMAGE_PATH}:latest" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        # Log in iff GHCR_PAT secret is available
        #if: ${{ secrets.GHCR_PAT != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: serviceacct-regents-umich-edu
          password: ${{ secrets.GHCR_PAT }}

      - name: Build, tag, and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          build-args: |
            IMAGE_TAG=${{ env.IMAGE_TAG }}
          # Push iff GHCR_PAT secret is available
          #push: ${{ secrets.GHCR_PAT != '' }}
          push: true
          tags: |
            ${{ env.LATEST_TAG }}
            ${{ env.TAGGED_IMAGE }}

      #- name: Notify if push is skipped
      #  if: secrets.GHCR_PAT == ''
      #  run: |
      #    echo "Skipping image push: secrets unavailable in PRs from forks."
