name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

# Use env to hold repo name, then convert to lowercase in the run steps
env:
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set image tag timestamp (UNIX epoch seconds)
        run: echo "IMAGE_TAG_TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${IMAGE_TAG_TIMESTAMP}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: serviceacct-regents-umich-edu
          password: ${{ secrets.GHCR_PAT }}

      - name: Tag image as latest
        run: docker tag my-image-name:${IMAGE_TAG_TIMESTAMP} ghcr.io/${GITHUB_REPOSITORY,,}/my-image-name:latest

      - name: Tag image with unique timestamp
        run: docker tag my-image-name:${IMAGE_TAG_TIMESTAMP} ghcr.io/${GITHUB_REPOSITORY,,}/my-image-name:${IMAGE_TAG_TIMESTAMP}

      - name: Push image with latest tag
        run: docker push ghcr.io/${GITHUB_REPOSITORY,,}/my-image-name:latest

      - name: Push image with unique timestamp tag
        run: docker push ghcr.io/${GITHUB_REPOSITORY,,}/my-image-name:${IMAGE_TAG_TIMESTAMP}
