name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  # repo and image name, converted to lowercase in the run steps
  GITHUB_REPOSITORY: ${{ github.repository }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set image variables
        run: |
          echo "IMAGE_TAG_TIMESTAMP=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_ENV
          echo "IMAGE_PATH=ghcr.io/${GITHUB_REPOSITORY,,}/${IMAGE_NAME,,}" >> $GITHUB_ENV

      - name: Set tag variables
        run: |
          echo "LATEST_TAG=${IMAGE_PATH}:latest" >> $GITHUB_ENV
          echo "TIMESTAMP_TAG=${IMAGE_PATH}:${IMAGE_TAG_TIMESTAMP}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: serviceacct-regents-umich-edu
          password: ${{ secrets.GHCR_PAT }}

      - name: Build, tag, and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          build-args: IMAGE_TAG_TIMESTAMP=${{ env.IMAGE_TAG_TIMESTAMP }}
          push: true
          tags: |
            ${{ env.LATEST_TAG }}
            ${{ env.TIMESTAMP_TAG }}
